name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy-production:
    runs-on: self-hosted
    steps:
      - name: executing remote ssh commands in server 1
        uses: appleboy/ssh-action@master
        with:
          host: 172.31.10.103
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
           mkdir ridham
