name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy-production:
    runs-on: self-hosted
    steps:
      - name: Get EC2 Instances by Tag and Fetch Private IPs
        id: get_ec2_ips
        run: |
          TAG_KEY="Owner"  
          TAG_VALUE="Ridham" 
          REGION="ap-south-1"
          
          INSTANCE_IDS=$(aws ec2 describe-instances --filters "Name=tag:${TAG_KEY},Values=${TAG_VALUE}" --query 'Reservations[*].Instances[*].InstanceId' --output text --region $REGION)
          PRIVATE_IPS=$(aws ec2 describe-instances --instance-ids $INSTANCE_IDS --region $REGION --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text)
          COMMA_SEPARATED_IPS=$(echo "$PRIVATE_IPS" | tr '\n' ',')
          COMMA_SEPARATED_IPS=${COMMA_SEPARATED_IPS%,}  # Remove the trailing comma

          # Output the IPs and save them to a file
          echo "Private IPs: $COMMA_SEPARATED_IPS"
          echo "$COMMA_SEPARATED_IPS" > /home/ubuntu/ipfile/ec2_private_ips.txt
