name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: self-hosted

    steps:
      - name: Get EC2 Instances by Tag and Fetch Private IPs
        id: get_ec2_ips
        run: |
          TAG_KEY="Owner"
          TAG_VALUE="Ridham"
          REGION="ap-south-1"
          
          # Fetch private IPs of EC2 instances based on the tag
          PRIVATE_IPS=$(aws ec2 describe-instances \
            --filters "Name=tag:${TAG_KEY},Values=${TAG_VALUE}" \
            --query 'Reservations[*].Instances[*].PrivateIpAddress' \
            --output text --region $REGION | tr '\t' ',')

          # Output the IPs as a GitHub environment variable
          echo "EC2_PRIVATE_IPS=$PRIVATE_IPS" >> $GITHUB_ENV

      - name: SSH into each EC2 instance and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_PRIVATE_IPS }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cat /etc/os-release 
